name: Python package

on: [push]

jobs:
  build_wheels_linux:
    name: Build wheels, manylinux
    runs-on: ubuntu-latest
    env:
      TAGLIB_HOME: taglib-install
      PYTAGLIB_CYTHONIZE: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Build wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.2-manylinux2010_x86_64
      with:
        python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39'
        build-requirements: 'cython'

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.whl
